[package]
name = "pdfbull"
version = "0.1.0"
description = "A lightweight PDF reader"
authors = ["SV-stark"]
edition = "2021"
license = "MIT"
homepage = "https://github.com/SV-stark/PDFbull"
repository = "https://github.com/SV-stark/PDFbull"
readme = "README.md"

[[bin]]
name = "pdfbull"
path = "src/main.rs"

[build-dependencies]
slint-build = "1.15"

[dependencies]
slint = { version = "1.15", features = ["renderer-winit-femtovg"] }
rfd = "0.14"
pdfium-render = "0.8"
image = "0.25"
rayon = "1.10"
